# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
- name: branchs
  displayName: Branch_Ivi
  type: object
  default: 
   branchs:
    - gitBranch: DEV 
      ivyBranch: BRC_S_ALELO_ACQ
    - gitBranch: HML 
      ivyBranch: BRC_S_ALELO_ACQ_HML
    - gitBranch: PROD 
      ivyBranch: BRC_S_ALELO_ACQ_PROD
    - gitBranch: PrePRD 
      ivyBranch: BRC_S_ALELO_ACQ_PrePRD
    - gitBranch: FIX 
      ivyBranch: BRC_S_ALELO_ACQ_FIX 
  
steps:    
  - ${{ each value in parameters.Branchs }}:
    - script: echo ${{ value.icyBranch }}  
      displayName: Test Dictionaries
