# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
- name: branch_Ivi
  displayName: Branch_Ivi
  type: object
  default: 
   branchs:
    - gitBranch: DEV 
      ivyBranch: BRC_S_ALELO_ACQ
    - gitBranch: HML 
      ivyBranch: BRC_S_ALELO_ACQ_HML
    - gitBranch: PROD 
      ivyBranch: BRC_S_ALELO_ACQ_PROD
    - gitBranch: PrePRD 
      ivyBranch: BRC_S_ALELO_ACQ_PrePRD
    - gitBranch: FIX 
      ivyBranch: BRC_S_ALELO_ACQ_FIX 
variables:
  name: CurrentBranch
  value: Pollito
steps: 
  - ${{ if eq(variables['CurrentBranch'], 'refs/heads/main') }}: 
    - script: echo I run only if Build.SourceBranch = refs/heads/main    
 # - ${{ if eq( $( CurrentBranch ), 'Pollito') }}:
  #  - script: |
  #      echo $(CurrentBranch)
  #      exit 1
  - ${{ each value in parameters.branch_Ivi.branchs }}:
    - ${{ if eq( value.gitBranch, 'DEV1') }}:
      - bash: echo '##vso[task.setvariable variable=CurrentBranch]${{value.ivyBranch}}'
  - ${{ if eq(variables['CurrentBranch'], 'Pollito') }}: 
    - script: |
        echo I run only if Build.SourceBranch = refs/heads/main
        exit 1

  

